package usdot.v2x.app.api.services;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import usdot.v2x.app.api.models.mqtt.MqttAclEntry;
import usdot.v2x.app.api.models.mqtt.MqttAclRequest;
import usdot.v2x.app.api.models.mqtt.MqttAclResponse;
import usdot.v2x.app.api.models.mqtt.MqttClient;
import usdot.v2x.app.api.repositories.MqttAclEntryRepository;
import usdot.v2x.app.api.repositories.MqttClientRepository;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class MqttAclServiceImpl implements MqttAclService {

    private final MqttAclEntryRepository aclEntryRepository;
    private final MqttClientRepository mqttClientRepository;

    @Value("${mosquitto.acl.file:/mosquitto/acl/acl.conf}")
    private String aclFilePath;

    @Override
    @Transactional
    public MqttAclResponse createOrUpdateAcl(MqttAclRequest request, String createdBy) {
        log.info("Creating or updating ACL entry for client: {} with topic: {}",
                request.getClientId(), request.getTopicPattern());

        // Verify client exists
        if (!mqttClientRepository.existsByClientId(request.getClientId())) {
            throw new IllegalArgumentException("Client not found: " + request.getClientId());
        }

        // Check if ACL entry already exists
        Optional<MqttAclEntry> existingEntry = aclEntryRepository.findByClientIdAndTopicPatternAndAccessType(
                request.getClientId(), request.getTopicPattern(), request.getAccessType());

        MqttAclEntry aclEntry;
        if (existingEntry.isPresent()) {
            aclEntry = existingEntry.get();
            aclEntry.setIsActive(true);
            log.debug("Updating existing ACL entry");
        } else {
            aclEntry = new MqttAclEntry();
            aclEntry.setClientId(request.getClientId());
            aclEntry.setTopicPattern(request.getTopicPattern());
            aclEntry.setAccessType(request.getAccessType());
            aclEntry.setCreatedBy(createdBy);
            aclEntry.setIsActive(true);
            log.debug("Creating new ACL entry");
        }

        MqttAclEntry savedEntry = aclEntryRepository.save(aclEntry);

        // Regenerate ACL file
        regenerateAclFile();

        log.info("Successfully saved ACL entry for client: {}", request.getClientId());
        return mapToResponse(savedEntry);
    }

    @Override
    public List<MqttAclResponse> getAclEntries(String clientId) {
        log.debug("Retrieving ACL entries for client: {}", clientId);
        return aclEntryRepository.findByClientIdAndIsActive(clientId, true)
                .stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional
    public boolean deleteAclEntry(Long aclId) {
        log.info("Deleting ACL entry: {}", aclId);

        Optional<MqttAclEntry> entryOpt = aclEntryRepository.findById(aclId);
        if (entryOpt.isEmpty()) {
            return false;
        }

        MqttAclEntry entry = entryOpt.get();
        entry.setIsActive(false);
        aclEntryRepository.save(entry);

        // Regenerate ACL file
        regenerateAclFile();

        log.info("Successfully deactivated ACL entry: {}", aclId);
        return true;
    }

    @Override
    @Transactional
    public boolean regenerateAclFile() {
        log.info("Regenerating Mosquitto ACL file");

        try {
            Path aclFile = Paths.get(aclFilePath);
            Path aclDir = aclFile.getParent();

            // Create directory if it doesn't exist
            if (aclDir != null && !Files.exists(aclDir)) {
                Files.createDirectories(aclDir);
            }

            // Get all active ACL entries
            List<MqttAclEntry> activeEntries = aclEntryRepository.findAllActive();

            // Build ACL file content
            StringBuilder aclContent = new StringBuilder();
            aclContent.append("# Mosquitto ACL Configuration\n");
            aclContent.append("# This file is automatically generated by V2X App API\n");
            aclContent.append("# DO NOT EDIT MANUALLY - Changes will be overwritten\n");
            aclContent
                    .append("# Uses certificate CN (Common Name) as username for certificate-based authentication\n\n");

            // Group by client ID and get certificate CN
            activeEntries.stream()
                    .collect(Collectors.groupingBy(MqttAclEntry::getClientId))
                    .forEach((clientId, entries) -> {
                        // Get the client to retrieve certificate CN
                        // For certificate-based auth, Mosquitto uses CN as username
                        String username = mqttClientRepository.findByClientId(clientId)
                                .map(client -> client.getCertificateCn() != null ? client.getCertificateCn() : clientId)
                                .orElse(clientId);

                        aclContent.append("user ").append(username).append("\n");
                        for (MqttAclEntry entry : entries) {
                            String accessType = mapAccessTypeToMosquitto(entry.getAccessType());
                            aclContent.append("  topic ").append(accessType).append(" ")
                                    .append(entry.getTopicPattern()).append("\n");
                        }
                        aclContent.append("\n");
                    });

            // Write to file
            Files.writeString(aclFile, aclContent.toString(),
                    StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE);

            log.info("Successfully regenerated ACL file with {} entries", activeEntries.size());

            return true;

        } catch (IOException e) {
            log.error("Failed to regenerate ACL file", e);
            return false;
        }
    }

    private String mapAccessTypeToMosquitto(MqttAclEntry.AccessType accessType) {
        return switch (accessType) {
            case read -> "read";
            case write -> "write";
            case readwrite -> "readwrite";
        };
    }

    private MqttAclResponse mapToResponse(MqttAclEntry entry) {
        return MqttAclResponse.builder()
                .id(entry.getId())
                .clientId(entry.getClientId())
                .topicPattern(entry.getTopicPattern())
                .accessType(entry.getAccessType())
                .isActive(entry.getIsActive())
                .createdAt(entry.getCreatedAt())
                .build();
    }
}
