name: Auto Update Swagger Docs

on:
  push:
    branches: [ develop, main ]
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'v2x-app-api/src/**'

jobs:
  generate-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for Gradle wrapper
        run: cd v2x-app-api && chmod +x gradlew

      - name: Build project
        run: cd v2x-app-api && ./gradlew clean build -x test

      - name: Start Spring Boot app
        run: |
          nohup cd v2x-app-api && ./gradlew bootRun &
          sleep 20

      - name: Generate OpenAPI docs
        run: cd v2x-app-api && ./gradlew generateOpenApiDocs

      - name: Commit and push updated docs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/openapi.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update Swagger docs"
          git push